import type { Template, Application, AnalyticsData, User } from '@/types'

export const mockUser: User = {
  id: '1',
  name: 'Shivam Kumar',
  email: 'shivam@example.com',
  avatar: '',
}

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'Software Engineer Application',
    senderEmail: 'shivam@example.com',
    subject: 'Application for {{position}} at {{company}}',
    body: 'Dear Hiring Team,\n\nI am writing to express my strong interest in the {{position}} position at {{company}}. With my background in software development and passion for building scalable applications, I am confident that I would be a valuable addition to your team.\n\nI have attached my resume for your review and look forward to the opportunity to discuss how my skills align with the needs of {{company}}.\n\nBest regards,\n{{name}}',
    createdAt: '2026-06-01',
    updatedAt: '2026-06-15',
    disabled: false,
  },
  {
    id: '2',
    name: 'Product Manager Role',
    senderEmail: 'shivam@example.com',
    subject: 'PM Application - {{position}} @ {{company}}',
    body: 'Hello {{company}} Team,\n\nI am excited to apply for the {{position}} role. My experience in product strategy and user-centric design makes me an ideal candidate to drive growth at {{company}}.\n\nLooking forward to connecting!\n\nCheers,\n{{name}}',
    createdAt: '2026-05-20',
    updatedAt: '2026-06-10',
    disabled: false,
  },
  {
    id: '3',
    name: 'Internship Application',
    senderEmail: 'shivam@example.com',
    subject: 'Internship Application - {{position}}',
    body: 'Dear {{company}} Recruitment Team,\n\nI am a passionate student eager to contribute to {{company}} as an intern in the {{position}} domain. I bring strong technical skills and a drive to learn.\n\nPlease find my resume attached.\n\nThank you,\n{{name}}',
    createdAt: '2026-06-10',
    updatedAt: '2026-06-12',
    disabled: false,
  },
  {
    id: '4',
    name: 'Follow Up Email',
    senderEmail: 'shivam@example.com',
    subject: 'Follow Up - {{position}} Application at {{company}}',
    body: 'Hi {{company}} Team,\n\nI wanted to follow up on my application for the {{position}} position. I remain very interested in joining {{company}} and would love to hear any updates.\n\nBest,\n{{name}}',
    createdAt: '2026-06-05',
    updatedAt: '2026-06-14',
    disabled: false,
  },
  {
    id: '5',
    name: 'Cold Outreach',
    senderEmail: 'shivam@example.com',
    subject: 'Exploring Opportunities at {{company}}',
    body: 'Hello {{company}},\n\nI am a {{name}}, reaching out to explore potential opportunities at {{company}}. I have been following your work and am impressed by your impact in the industry.\n\nI would love to connect and discuss how I can contribute.\n\nBest regards,\n{{name}}',
    createdAt: '2026-06-08',
    updatedAt: '2026-06-13',
    disabled: true,
  },
]

export const mockApplications: Application[] = [
  { id: '1', company: 'Google', email: 'hr@google.com', position: 'Senior Frontend Engineer', location: 'Bangalore, India', website: 'https://careers.google.com', source: 'LinkedIn', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-20', status: 'Applied' },
  { id: '2', company: 'Stripe', email: 'careers@stripe.com', position: 'Product Designer', location: 'Remote', source: 'Cutshort', templateId: '2', templateName: 'Product Manager Role', appliedDate: '2026-06-19', status: 'Viewed' },
  { id: '3', company: 'Vercel', email: 'jobs@vercel.com', position: 'Frontend Engineer', location: 'San Francisco, USA', source: 'LinkedIn', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-18', status: 'Interview' },
  { id: '4', company: 'Linear', email: 'team@linear.app', position: 'Full Stack Engineer', location: 'Remote', website: 'https://linear.app/jobs', source: 'Company Website', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-17', status: 'Pending' },
  { id: '5', company: 'Notion', email: 'jobs@notion.so', position: 'Software Engineer', location: 'New York, USA', source: 'LinkedIn', templateId: '3', templateName: 'Internship Application', appliedDate: '2026-06-16', status: 'Rejected' },
  { id: '6', company: 'Framer', email: 'careers@framer.com', position: 'React Developer', location: 'Amsterdam', source: 'Indeed', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-15', status: 'Offer' },
  { id: '7', company: 'Resend', email: 'founders@resend.com', position: 'Frontend Engineer', location: 'Remote', source: 'Internshala', templateId: '2', templateName: 'Product Manager Role', appliedDate: '2026-06-14', status: 'Applied' },
  { id: '8', company: 'Clerk', email: 'jobs@clerk.dev', position: 'Developer Advocate', location: 'Remote', source: 'LinkedIn', templateId: '4', templateName: 'Follow Up Email', appliedDate: '2026-06-13', status: 'Interview' },
  { id: '9', company: 'Meta', email: 'recruiting@meta.com', position: 'Software Engineer', location: 'Menlo Park, USA', source: 'Naukri', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-12', status: 'Pending' },
  { id: '10', company: 'Apple', email: 'jobs@apple.com', position: 'UI Engineer', location: 'Cupertino, USA', source: 'LinkedIn', templateId: '5', templateName: 'Cold Outreach', appliedDate: '2026-06-11', status: 'Rejected' },
  { id: '11', company: 'Netflix', email: 'talent@netflix.com', position: 'Senior UI Engineer', location: 'Los Gatos, USA', source: 'LinkedIn', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-10', status: 'Applied' },
  { id: '12', company: 'Spotify', email: 'jobs@spotify.com', position: 'Frontend Developer', location: 'Stockholm, Sweden', source: 'Indeed', templateId: '3', templateName: 'Internship Application', appliedDate: '2026-06-09', status: 'Viewed' },
  { id: '13', company: 'Amazon', email: 'jobs@amazon.com', position: 'SDE II', location: 'Seattle, USA', source: 'LinkedIn', templateId: '1', templateName: 'Software Engineer Application', appliedDate: '2026-06-08', status: 'Interview' },
  { id: '14', company: 'Microsoft', email: 'recruit@microsoft.com', position: 'Software Engineer', location: 'Hyderabad, India', source: 'Naukri', templateId: '2', templateName: 'Product Manager Role', appliedDate: '2026-06-07', status: 'Pending' },
  { id: '15', company: 'GitHub', email: 'jobs@github.com', position: 'Developer Relations', location: 'Remote', source: 'Company Website', templateId: '4', templateName: 'Follow Up Email', appliedDate: '2026-06-06', status: 'Applied' },
]

export const mockAnalytics: AnalyticsData = {
  totalApplications: 47,
  totalTemplates: 5,
  emailsSent: 42,
  successRate: 68,
  thisWeekApplies: 8,
  applicationsByMonth: [
    { month: 'Jan', count: 3 },
    { month: 'Feb', count: 7 },
    { month: 'Mar', count: 5 },
    { month: 'Apr', count: 9 },
    { month: 'May', count: 12 },
    { month: 'Jun', count: 11 },
  ],
  sourceDistribution: [
    { source: 'LinkedIn', count: 18 },
    { source: 'Naukri', count: 8 },
    { source: 'Indeed', count: 7 },
    { source: 'Cutshort', count: 5 },
    { source: 'Company Website', count: 6 },
    { source: 'Internshala', count: 3 },
  ],
  emailSentTrend: [
    { date: 'Jun 1', count: 2 },
    { date: 'Jun 5', count: 5 },
    { date: 'Jun 10', count: 8 },
    { date: 'Jun 15', count: 6 },
    { date: 'Jun 20', count: 10 },
    { date: 'Jun 25', count: 7 },
  ],
  recentActivity: [
    { action: 'Applied', detail: 'Google - Senior Frontend Engineer', time: '2 hours ago' },
    { action: 'Interview', detail: 'Vercel - Frontend Engineer', time: '1 day ago' },
    { action: 'Viewed', detail: 'Stripe - Product Designer', time: '2 days ago' },
    { action: 'Offer', detail: 'Framer - React Developer', time: '3 days ago' },
    { action: 'Rejected', detail: 'Notion - Software Engineer', time: '5 days ago' },
    { action: 'Applied', detail: 'Resend - Frontend Engineer', time: '1 week ago' },
  ],
  stats: {
    applications: 47,
    responses: 28,
    interviews: 12,
    offers: 3,
    pending: 15,
  },
}
